
# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 16384
num_eval_envs: 4
num_agents: ${task.env.numAgents}
log_interval: 5

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: 1000
max_env_steps: 50_000_000

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
cuda_id: 0
sim_device: 'cuda:${cuda_id}'
# device to run RL
rl_device: 'cuda:${cuda_id}'
graphics_device_id: ${cuda_id}

params:
  # ppo
  num_steps: 8
  num_mini_batch: 16
  ppo_epoch: 5
  clip_param: 0.2
  entropy_coef: 0.01

  # network
  activation_id: 1
  attn_N: 1
  attn_heads: 4
  attn_size: 64
  layer_N: 3
  hidden_size: 128
  lr: 0.0005
  critic_lr: 0.0005
  recurrent_N: 1

  sde: False
  algorithm_name: mappo
  aux_epoch: 5
  buffer_length: 10000
  clone_coef: 1.0
  cnn_layers_params: null
  cuda: true
  cuda_deterministic: true
  data_chunk_length: 16
  dropout: 0.0
  eval_episodes: 32
  eval_interval: 25
  explored_ratio_threshold: 0.9
  gae_lambda: 0.95
  gain: 0.01
  gamma: 0.99
  huber_delta: 10.0
  ifi: 0.1
  influence_layer_N: 1
  log_interval: 5
  max_grad_norm: 10.0
  metric_T: 5
  model_dir: null
  opti_eps: 1.0e-05
  policy_value_loss_coef: 1
  render_episodes: 5
  restart_easy: 0.2
  restart_p: 0.7
  save_gifs: false
  save_interval: 1
  seed: 1
  share_policy: true
  sigma_max: 0.9
  sigma_min: 0.5
  stacked_frames: 1
  success_threshold: 0.9
  tanh_normal: false
  tau: 0.995
  use_attn: false
  use_attn_internal: true
  use_average_pool: true
  use_cat_self: true
  use_centralized_V: true
  use_clipped_value_loss: true
  use_conv1d: false
  use_diversified: false
  use_eval: false
  use_feature_normalization: true
  use_gae: true
  use_huber_loss: true
  use_influence_policy: false
  use_linear_lr_decay: false
  use_max_grad_norm: true
  use_maxpool2d: false
  use_naive_recurrent_policy: false
  use_obs_instead_of_state: false
  use_orthogonal: true
  use_policy_active_masks: true
  use_policy_vhead: false
  use_popart: false
  use_proper_time_limits: false
  use_recurrent_policy: False
  use_render: false
  use_single_network: false
  use_stacked_frames: false
  use_start_states: false
  use_states_clip: false
  use_value_active_masks: true
  use_valuenorm: true
  use_wandb: true
  user_name: zoeyuchao
  value_loss_coef: 1
  wandb_name: zoeyuchao
  weight_decay: 0

wandb_activate: True
wandb_group: ${task.name}
wandb_name: ${task.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
capture_video: True
capture_video_freq: 4
capture_video_len: ${task.env.maxEpisodeLength}
force_render: True

# disables rendering
headless: False

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

defaults:
  - task: QuadrotorOccupationI
  - _self_
